### ISSUE TITLE
tradfri-light-control RGB color not working

### ISSUE THREAD

**Issue by muleooo** [mjwwit/node-red-contrib-ikea-tradfri#8] opened 2021-06-07 10:15 UTC
Hi,

I'm on v 0.4.6 and trying to set the color of an IKEA LED1624G9 color bulb using tradfri-light-control but nothing seems to be happening.

While I can trigger it on or off and change the brightness just fine, trying to set the color with payload color property does not work:
{"onOff": true,
"brightness": 10,
"color": "#00ff00"}

Instead of the light turning green it stays a cold bluish white. 

Also trying to send any command without the color also makes the light revert from whatever it was previously set to, to bluish white.

Could you please take a look?
Thanks,
Muleo

**Comment by mjwwit** [comment] 2021-06-07 10:26
Thanks for reporting this, but it's a duplicate of #6. Please keep an eye on that issue to stay up-to-date.

**Closed by mjwwit** 2021-06-07 10:26 UTC
